apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rendered/alloy/charts/crds/crds/monitoring.grafana.com_podlogs.yaml
  - rendered/alloy/templates/controllers/daemonset.yaml
  - rendered/alloy/templates/configmap.yaml
  - rendered/alloy/templates/rbac.yaml
  - rendered/alloy/templates/service.yaml
  - rendered/alloy/templates/serviceaccount.yaml