apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-apps

resources:
  - base/deployment.yaml
  - base/service.yaml
  - base/redis-insight/deployment.yaml
  - base/redis-insight/http-route.yaml
  - base/redis-insight/service.yaml

commonLabels:
  stack: demo-apps