alertmanager:
  enabled: true

grafana:
  enabled: true
  admin:
    existingSecret: grafana-admin
    userKey: admin-user
    passwordKey: admin-password

kubeProxy:
  enabled: false

prometheus:
  enabled: true

  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    scrapeConfigSelectorNilUsesHelmValues: false

    retention: 7d
    retentionSize: 1GiB

    replicas: 1
    shards: 1

    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        memory: 1Gi

    storageSpec: {}
    ## Using PersistentVolumeClaim
    ##
    #  volumeClaimTemplate:
    #    spec:
    #      storageClassName: gluster
    #      accessModes: ["ReadWriteOnce"]
    #      resources:
    #        requests:
    #          storage: 50Gi
    #      selector: {}

    ## Using tmpfs volume
    ##
    #  emptyDir:
    #    medium: Memory