# argocd/apps/demo-apps-namespace.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-apps-namespace
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"    # 최우선 순위
spec:
  project: default
  source:
    repoURL: https://github.com/chopha66/k8s-platform.git
    targetRevision: master
    path: demo-apps/namespace/kustomize/overlays/base
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: { prune: true, selfHeal: true }