# backend — 내부 서비스 (frontend가 호출)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        tier: backend
    spec:
      containers:
        - name: app
          image: quay.io/brancz/prometheus-example-app:v0.5.0
          ports:
            - name: http
              containerPort: 8080
            - name: alternative
              containerPort: 9090
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              memory: 64Mi
      # 파드 레벨 securityContext
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534 # nobody 유저
        seccompProfile:
          type: RuntimeDefault
        containers:
          - name: app
            # 컨테이너 레벨 securityContext
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop: [ "ALL" ]
              runAsNonRoot: true